const { Inject, Injectable, Logger, NotFoundException, BadRequestException, Optional } = require('@nestjs/common');
const { PrismaService } = require('../../config/prisma.service');
const { MikroTikService } = require('./mikrotik.service');
const { IspNotificationService } = require('./isp-notification.service');

@Injectable()
class IspBillingService {
  constructor(
    @Inject(PrismaService) prismaService,
    @Inject(MikroTikService) mikroTikService,
    @Optional() @Inject(IspNotificationService) notificationService = null,
  ) {
    this.prisma = prismaService;
    this.mikroTik = mikroTikService;
    this.notifications = notificationService;
    this.logger = new Logger(IspBillingService.name);
  }

  // ──────────────────────────────────────────────
  // BILLING SETTINGS
  // ──────────────────────────────────────────────

  async getSettings() {
    let settings = await this.prisma.ispBillingSettings.findFirst();
    if (!settings) {
      settings = await this.prisma.ispBillingSettings.create({ data: {} });
    }
    return settings;
  }

  async updateSettings(data) {
    const settings = await this.getSettings();
    return this.prisma.ispBillingSettings.update({
      where: { id: settings.id },
      data,
    });
  }

  // ──────────────────────────────────────────────
  // INVOICE NUMBERING
  // ──────────────────────────────────────────────

  async nextInvoiceNumber() {
    const settings = await this.getSettings();
    const prefix = settings.invoicePrefix || 'ISP';
    const count = await this.prisma.ispInvoice.count();
    const num = String(count + 1).padStart(5, '0');
    return `${prefix}-${num}`;
  }

  async nextPaymentNumber() {
    const count = await this.prisma.ispPayment.count();
    const num = String(count + 1).padStart(5, '0');
    return `PAY-${num}`;
  }

  // ──────────────────────────────────────────────
  // INVOICES - CRUD
  // ──────────────────────────────────────────────

  async listInvoices({ page = 1, limit = 50, status, customerId, search } = {}) {
    const where = {};
    if (status) where.status = status;
    if (customerId) where.customerId = customerId;
    if (search) {
      where.OR = [
        { invoiceNumber: { contains: search, mode: 'insensitive' } },
        { customer: { firstName: { contains: search, mode: 'insensitive' } } },
        { customer: { lastName: { contains: search, mode: 'insensitive' } } },
        { customer: { pppoeUsername: { contains: search, mode: 'insensitive' } } },
      ];
    }

    const [items, total] = await Promise.all([
      this.prisma.ispInvoice.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        include: {
          customer: { select: { id: true, firstName: true, lastName: true, pppoeUsername: true, email: true } },
          items: true,
          payments: true,
        },
      }),
      this.prisma.ispInvoice.count({ where }),
    ]);
    return { items, total, page, pages: Math.ceil(total / limit) };
  }

  async getInvoice(id) {
    const invoice = await this.prisma.ispInvoice.findUnique({
      where: { id },
      include: {
        customer: true,
        items: true,
        payments: { orderBy: { paymentDate: 'desc' } },
      },
    });
    if (!invoice) throw new NotFoundException('Invoice not found');
    return invoice;
  }

  async createInvoice(data) {
    const { customerId, items, notes, dueDate, taxRate } = data;

    const customer = await this.prisma.ispCustomer.findUnique({ where: { id: customerId } });
    if (!customer) throw new NotFoundException('Customer not found');

    const settings = await this.getSettings();
    const invoiceNumber = await this.nextInvoiceNumber();
    const rate = taxRate !== undefined ? taxRate : Number(settings.taxRate);

    // Calculate totals
    let subtotal = 0;
    const invoiceItems = (items || []).map((item) => {
      const qty = Number(item.quantity) || 1;
      const price = Number(item.unitPrice) || 0;
      const total = qty * price;
      subtotal += total;
      return {
        description: item.description,
        quantity: qty,
        unitPrice: price,
        total,
      };
    });

    const taxAmount = Math.round(subtotal * rate * 100) / 100;
    const totalAmount = subtotal + taxAmount;

    const now = new Date();
    const due = dueDate ? new Date(dueDate) : new Date(now.getTime() + settings.paymentTermsDays * 86400000);

    const invoice = await this.prisma.ispInvoice.create({
      data: {
        invoiceNumber,
        customerId,
        issueDate: now,
        dueDate: due,
        subtotal,
        taxRate: rate,
        taxAmount,
        totalAmount,
        amountPaid: 0,
        balanceDue: totalAmount,
        notes: notes || null,
        periodStart: data.periodStart ? new Date(data.periodStart) : null,
        periodEnd: data.periodEnd ? new Date(data.periodEnd) : null,
        autoGenerated: data.autoGenerated || false,
        items: { create: invoiceItems },
      },
      include: { customer: true, items: true },
    });

    // Send invoice notification
    if (this.notifications) {
      this.notifications.notifyInvoiceCreated(customer, invoice, settings).catch((e) =>
        this.logger.error(`Invoice notification failed: ${e.message}`));
    }

    return invoice;
  }

  async updateInvoiceStatus(id, status) {
    return this.prisma.ispInvoice.update({
      where: { id },
      data: { status },
    });
  }

  async deleteInvoice(id) {
    return this.prisma.ispInvoice.delete({ where: { id } });
  }

  // ──────────────────────────────────────────────
  // PAYMENTS
  // ──────────────────────────────────────────────

  async recordPayment(data) {
    const { invoiceId, amount, method, reference, notes, paymentDate } = data;

    const invoice = await this.prisma.ispInvoice.findUnique({
      where: { id: invoiceId },
      include: { customer: true },
    });
    if (!invoice) throw new NotFoundException('Invoice not found');

    const payAmount = Number(amount);
    if (payAmount <= 0) throw new BadRequestException('Payment amount must be positive');

    const newAmountPaid = Number(invoice.amountPaid) + payAmount;
    const newBalanceDue = Number(invoice.totalAmount) - newAmountPaid;

    let newStatus = invoice.status;
    if (newBalanceDue <= 0) {
      newStatus = 'PAID';
    } else if (newAmountPaid > 0) {
      newStatus = 'PARTIALLY_PAID';
    }

    const paymentNumber = await this.nextPaymentNumber();

    const [payment] = await this.prisma.$transaction([
      this.prisma.ispPayment.create({
        data: {
          paymentNumber,
          invoiceId,
          amount: payAmount,
          method: method || 'CASH',
          reference: reference || null,
          notes: notes || null,
          paymentDate: paymentDate ? new Date(paymentDate) : new Date(),
        },
      }),
      this.prisma.ispInvoice.update({
        where: { id: invoiceId },
        data: {
          amountPaid: newAmountPaid,
          balanceDue: Math.max(0, newBalanceDue),
          status: newStatus,
          paidDate: newStatus === 'PAID' ? new Date() : null,
        },
      }),
    ]);

    // Send payment notification
    if (this.notifications && invoice.customer) {
      this.notifications.notifyPaymentReceived(invoice.customer, payment, invoice).catch((e) =>
        this.logger.error(`Payment notification failed: ${e.message}`));
    }

    // Auto-reactivate: if invoice is now PAID, check if customer has no more overdue invoices
    if (newStatus === 'PAID' && invoice.customer) {
      try {
        await this.tryAutoReactivate(invoice.customer.id);
      } catch (err) {
        this.logger.warn(`Auto-reactivate failed for customer ${invoice.customer.id}: ${err.message}`);
      }
    }

    return payment;
  }

  async listPayments({ page = 1, limit = 50, invoiceId } = {}) {
    const where = {};
    if (invoiceId) where.invoiceId = invoiceId;

    const [items, total] = await Promise.all([
      this.prisma.ispPayment.findMany({
        where,
        orderBy: { paymentDate: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        include: {
          invoice: {
            select: { invoiceNumber: true, customerId: true, customer: { select: { firstName: true, lastName: true, pppoeUsername: true } } },
          },
        },
      }),
      this.prisma.ispPayment.count({ where }),
    ]);
    return { items, total, page, pages: Math.ceil(total / limit) };
  }

  // ──────────────────────────────────────────────
  // AUTO-GENERATE MONTHLY INVOICES
  // ──────────────────────────────────────────────

  async generateMonthlyInvoices(servicePlans) {
    // servicePlans: { [profileName]: { description, price } }
    const settings = await this.getSettings();
    const customers = await this.prisma.ispCustomer.findMany({
      where: { status: 'ACTIVE', billingType: 'RECURRING' },
    });

    const now = new Date();
    const periodStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    const monthLabel = now.toLocaleString('en-GB', { month: 'long', year: 'numeric' });

    const results = { generated: 0, skipped: 0, errors: [] };

    for (const cust of customers) {
      try {
        // Check if invoice already exists for this month
        const existing = await this.prisma.ispInvoice.findFirst({
          where: {
            customerId: cust.id,
            periodStart: { gte: periodStart },
            periodEnd: { lte: new Date(periodEnd.getTime() + 86400000) },
          },
        });

        if (existing) {
          results.skipped++;
          continue;
        }

        // Get plan price from servicePlans map (keyed by MikroTik profile name)
        // You'll need to pass the profile name -> price mapping
        const plan = servicePlans?.[cust.pppoeUsername];
        if (!plan || !plan.price) {
          results.skipped++;
          continue;
        }

        await this.createInvoice({
          customerId: cust.id,
          items: [{
            description: `Internet Service - ${plan.description || plan.profileName || 'Monthly'} (${monthLabel})`,
            quantity: 1,
            unitPrice: plan.price,
          }],
          periodStart,
          periodEnd,
          autoGenerated: true,
          notes: `Auto-generated for ${monthLabel}`,
        });

        results.generated++;
      } catch (err) {
        results.errors.push({ customer: cust.pppoeUsername, error: err.message });
      }
    }

    this.logger.log(`Monthly invoices: ${results.generated} generated, ${results.skipped} skipped, ${results.errors.length} errors`);
    return results;
  }

  // ──────────────────────────────────────────────
  // OVERDUE CHECK
  // ──────────────────────────────────────────────

  async markOverdueInvoices() {
    const now = new Date();

    // Find overdue invoices with customer info before updating
    const overdueInvoices = await this.prisma.ispInvoice.findMany({
      where: {
        status: { in: ['DRAFT', 'SENT'] },
        dueDate: { lt: now },
        balanceDue: { gt: 0 },
      },
      include: { customer: true },
    });

    if (overdueInvoices.length === 0) return { count: 0 };

    const result = await this.prisma.ispInvoice.updateMany({
      where: { id: { in: overdueInvoices.map((i) => i.id) } },
      data: { status: 'OVERDUE' },
    });

    // Send overdue notifications
    if (this.notifications) {
      for (const inv of overdueInvoices) {
        if (inv.customer) {
          this.notifications.notifyOverdueReminder(inv.customer, inv).catch((e) =>
            this.logger.error(`Overdue notification failed for ${inv.invoiceNumber}: ${e.message}`));
        }
      }
    }

    this.logger.log(`Marked ${result.count} invoices as overdue`);
    return { count: result.count };
  }

  // ──────────────────────────────────────────────
  // DASHBOARD STATS
  // ──────────────────────────────────────────────

  async getDashboardStats() {
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

    const [
      totalInvoices,
      paidInvoices,
      overdueInvoices,
      draftInvoices,
      totalRevenue,
      monthRevenue,
      totalOutstanding,
    ] = await Promise.all([
      this.prisma.ispInvoice.count(),
      this.prisma.ispInvoice.count({ where: { status: 'PAID' } }),
      this.prisma.ispInvoice.count({ where: { status: 'OVERDUE' } }),
      this.prisma.ispInvoice.count({ where: { status: 'DRAFT' } }),
      this.prisma.ispInvoice.aggregate({ _sum: { amountPaid: true } }),
      this.prisma.ispPayment.aggregate({
        _sum: { amount: true },
        where: { paymentDate: { gte: monthStart } },
      }),
      this.prisma.ispInvoice.aggregate({
        _sum: { balanceDue: true },
        where: { status: { in: ['SENT', 'OVERDUE', 'PARTIALLY_PAID'] } },
      }),
    ]);

    return {
      totalInvoices,
      paidInvoices,
      overdueInvoices,
      draftInvoices,
      totalRevenue: Number(totalRevenue._sum.amountPaid || 0),
      monthRevenue: Number(monthRevenue._sum.amount || 0),
      totalOutstanding: Number(totalOutstanding._sum.balanceDue || 0),
    };
  }

  // ──────────────────────────────────────────────
  // CUSTOMER BILLING SUMMARY
  // ──────────────────────────────────────────────

  async getCustomerBillingSummary(customerId) {
    const [invoices, payments] = await Promise.all([
      this.prisma.ispInvoice.findMany({
        where: { customerId },
        orderBy: { createdAt: 'desc' },
        include: { items: true, payments: true },
      }),
      this.prisma.ispPayment.findMany({
        where: { invoice: { customerId } },
        orderBy: { paymentDate: 'desc' },
      }),
    ]);

    const totalInvoiced = invoices.reduce((sum, inv) => sum + Number(inv.totalAmount), 0);
    const totalPaid = invoices.reduce((sum, inv) => sum + Number(inv.amountPaid), 0);
    const totalOutstanding = invoices.reduce((sum, inv) => sum + Number(inv.balanceDue), 0);
    const overdueCount = invoices.filter((inv) => inv.status === 'OVERDUE').length;

    return {
      invoices,
      payments,
      totalInvoiced,
      totalPaid,
      totalOutstanding,
      overdueCount,
    };
  }

  // ──────────────────────────────────────────────
  // AUTO-SUSPENSION
  // ──────────────────────────────────────────────

  async autoSuspendOverdueClients() {
    const settings = await this.getSettings();
    if (!settings.enableAutoSuspend) {
      return { suspended: 0, message: 'Auto-suspend is disabled' };
    }

    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - settings.autoSuspendDays);

    // Find active customers who have overdue invoices past the cutoff
    const overdueCustomers = await this.prisma.ispCustomer.findMany({
      where: {
        status: 'ACTIVE',
        invoices: {
          some: {
            status: 'OVERDUE',
            dueDate: { lt: cutoffDate },
            balanceDue: { gt: 0 },
          },
        },
      },
      include: {
        invoices: {
          where: { status: 'OVERDUE', balanceDue: { gt: 0 } },
          select: { id: true, invoiceNumber: true, balanceDue: true, dueDate: true },
          orderBy: { dueDate: 'asc' },
          take: 5,
        },
      },
    });

    const results = { suspended: 0, errors: [], details: [] };

    for (const cust of overdueCustomers) {
      try {
        // Disable PPPoE secret on MikroTik
        await this.mikroTik.disableSecret(cust.pppoeUsername);

        // Update customer status to BLOCKED
        await this.prisma.ispCustomer.update({
          where: { id: cust.id },
          data: { status: 'BLOCKED' },
        });

        results.suspended++;
        results.details.push({
          customerId: cust.id,
          username: cust.pppoeUsername,
          name: `${cust.firstName} ${cust.lastName}`,
          overdueInvoices: cust.invoices.length,
          totalOwed: cust.invoices.reduce((s, inv) => s + Number(inv.balanceDue), 0),
        });

        // Send suspension notification
        if (this.notifications) {
          this.notifications.notifySuspended(cust).catch((e) =>
            this.logger.error(`Suspension notification failed for ${cust.pppoeUsername}: ${e.message}`));
        }

        this.logger.log(`Auto-suspended: ${cust.pppoeUsername} (${cust.invoices.length} overdue invoices)`);
      } catch (err) {
        results.errors.push({ username: cust.pppoeUsername, error: err.message });
        this.logger.warn(`Failed to suspend ${cust.pppoeUsername}: ${err.message}`);
      }
    }

    this.logger.log(`Auto-suspension: ${results.suspended} suspended, ${results.errors.length} errors`);
    return results;
  }

  async tryAutoReactivate(customerId) {
    const customer = await this.prisma.ispCustomer.findUnique({
      where: { id: customerId },
      include: {
        invoices: {
          where: { status: 'OVERDUE', balanceDue: { gt: 0 } },
          select: { id: true },
        },
      },
    });

    if (!customer || customer.status !== 'BLOCKED') return null;

    // Only reactivate if no more overdue invoices with balance
    if (customer.invoices.length > 0) return null;

    // Re-enable PPPoE secret on MikroTik
    await this.mikroTik.enableSecret(customer.pppoeUsername);

    // Update customer status to ACTIVE
    await this.prisma.ispCustomer.update({
      where: { id: customerId },
      data: { status: 'ACTIVE' },
    });

    // Send reactivation notification
    if (this.notifications) {
      this.notifications.notifyReactivated(customer).catch((e) =>
        this.logger.error(`Reactivation notification failed for ${customer.pppoeUsername}: ${e.message}`));
    }

    this.logger.log(`Auto-reactivated: ${customer.pppoeUsername} (all overdue invoices cleared)`);
    return { reactivated: true, username: customer.pppoeUsername };
  }

  // ── Manual suspend / unsuspend ─────────────────

  async suspendClient(customerId) {
    const customer = await this.prisma.ispCustomer.findUnique({ where: { id: customerId } });
    if (!customer) throw new NotFoundException('Customer not found');
    if (customer.status === 'BLOCKED') {
      return { message: 'Customer is already suspended' };
    }

    await this.mikroTik.disableSecret(customer.pppoeUsername);
    await this.prisma.ispCustomer.update({
      where: { id: customerId },
      data: { status: 'BLOCKED' },
    });

    if (this.notifications) {
      this.notifications.notifySuspended(customer).catch((e) =>
        this.logger.error(`Manual suspend notification failed: ${e.message}`));
    }

    this.logger.log(`Manually suspended: ${customer.pppoeUsername}`);
    return { success: true, message: `${customer.pppoeUsername} suspended` };
  }

  async unsuspendClient(customerId) {
    const customer = await this.prisma.ispCustomer.findUnique({ where: { id: customerId } });
    if (!customer) throw new NotFoundException('Customer not found');
    if (customer.status === 'ACTIVE') {
      return { message: 'Customer is already active' };
    }

    await this.mikroTik.enableSecret(customer.pppoeUsername);
    await this.prisma.ispCustomer.update({
      where: { id: customerId },
      data: { status: 'ACTIVE' },
    });

    if (this.notifications) {
      this.notifications.notifyReactivated(customer).catch((e) =>
        this.logger.error(`Manual unsuspend notification failed: ${e.message}`));
    }

    this.logger.log(`Manually unsuspended: ${customer.pppoeUsername}`);
    return { success: true, message: `${customer.pppoeUsername} reactivated` };
  }

  // ── Suspension summary ─────────────────────────

  async getSuspensionSummary() {
    const settings = await this.getSettings();
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - settings.autoSuspendDays);

    const [suspendedCount, atRiskCount, recentlySuspended] = await Promise.all([
      // Currently suspended
      this.prisma.ispCustomer.count({ where: { status: 'BLOCKED' } }),
      // Active but have overdue invoices (at risk of suspension)
      this.prisma.ispCustomer.count({
        where: {
          status: 'ACTIVE',
          invoices: {
            some: { status: 'OVERDUE', balanceDue: { gt: 0 } },
          },
        },
      }),
      // Blocked customers with details
      this.prisma.ispCustomer.findMany({
        where: { status: 'BLOCKED' },
        select: {
          id: true,
          pppoeUsername: true,
          firstName: true,
          lastName: true,
          phone: true,
          email: true,
          invoices: {
            where: { status: { in: ['OVERDUE', 'PARTIALLY_PAID'] }, balanceDue: { gt: 0 } },
            select: { invoiceNumber: true, balanceDue: true, dueDate: true },
            orderBy: { dueDate: 'asc' },
          },
        },
        orderBy: { lastName: 'asc' },
        take: 100,
      }),
    ]);

    return {
      suspendedCount,
      atRiskCount,
      autoSuspendEnabled: settings.enableAutoSuspend,
      autoSuspendDays: settings.autoSuspendDays,
      recentlySuspended: recentlySuspended.map((c) => ({
        ...c,
        totalOwed: c.invoices.reduce((s, inv) => s + Number(inv.balanceDue), 0),
      })),
    };
  }
}

module.exports = { IspBillingService };
