const { Inject, Injectable, Logger, NotFoundException, BadRequestException } = require('@nestjs/common');
const { PrismaService } = require('../../config/prisma.service');

@Injectable()
class IspBillingService {
  constructor(@Inject(PrismaService) prismaService) {
    this.prisma = prismaService;
    this.logger = new Logger(IspBillingService.name);
  }

  // ──────────────────────────────────────────────
  // BILLING SETTINGS
  // ──────────────────────────────────────────────

  async getSettings() {
    let settings = await this.prisma.ispBillingSettings.findFirst();
    if (!settings) {
      settings = await this.prisma.ispBillingSettings.create({ data: {} });
    }
    return settings;
  }

  async updateSettings(data) {
    const settings = await this.getSettings();
    return this.prisma.ispBillingSettings.update({
      where: { id: settings.id },
      data,
    });
  }

  // ──────────────────────────────────────────────
  // INVOICE NUMBERING
  // ──────────────────────────────────────────────

  async nextInvoiceNumber() {
    const settings = await this.getSettings();
    const prefix = settings.invoicePrefix || 'ISP';
    const count = await this.prisma.ispInvoice.count();
    const num = String(count + 1).padStart(5, '0');
    return `${prefix}-${num}`;
  }

  async nextPaymentNumber() {
    const count = await this.prisma.ispPayment.count();
    const num = String(count + 1).padStart(5, '0');
    return `PAY-${num}`;
  }

  // ──────────────────────────────────────────────
  // INVOICES - CRUD
  // ──────────────────────────────────────────────

  async listInvoices({ page = 1, limit = 50, status, customerId, search } = {}) {
    const where = {};
    if (status) where.status = status;
    if (customerId) where.customerId = customerId;
    if (search) {
      where.OR = [
        { invoiceNumber: { contains: search, mode: 'insensitive' } },
        { customer: { firstName: { contains: search, mode: 'insensitive' } } },
        { customer: { lastName: { contains: search, mode: 'insensitive' } } },
        { customer: { pppoeUsername: { contains: search, mode: 'insensitive' } } },
      ];
    }

    const [items, total] = await Promise.all([
      this.prisma.ispInvoice.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        include: {
          customer: { select: { id: true, firstName: true, lastName: true, pppoeUsername: true, email: true } },
          items: true,
          payments: true,
        },
      }),
      this.prisma.ispInvoice.count({ where }),
    ]);
    return { items, total, page, pages: Math.ceil(total / limit) };
  }

  async getInvoice(id) {
    const invoice = await this.prisma.ispInvoice.findUnique({
      where: { id },
      include: {
        customer: true,
        items: true,
        payments: { orderBy: { paymentDate: 'desc' } },
      },
    });
    if (!invoice) throw new NotFoundException('Invoice not found');
    return invoice;
  }

  async createInvoice(data) {
    const { customerId, items, notes, dueDate, taxRate } = data;

    const customer = await this.prisma.ispCustomer.findUnique({ where: { id: customerId } });
    if (!customer) throw new NotFoundException('Customer not found');

    const settings = await this.getSettings();
    const invoiceNumber = await this.nextInvoiceNumber();
    const rate = taxRate !== undefined ? taxRate : Number(settings.taxRate);

    // Calculate totals
    let subtotal = 0;
    const invoiceItems = (items || []).map((item) => {
      const qty = Number(item.quantity) || 1;
      const price = Number(item.unitPrice) || 0;
      const total = qty * price;
      subtotal += total;
      return {
        description: item.description,
        quantity: qty,
        unitPrice: price,
        total,
      };
    });

    const taxAmount = Math.round(subtotal * rate * 100) / 100;
    const totalAmount = subtotal + taxAmount;

    const now = new Date();
    const due = dueDate ? new Date(dueDate) : new Date(now.getTime() + settings.paymentTermsDays * 86400000);

    return this.prisma.ispInvoice.create({
      data: {
        invoiceNumber,
        customerId,
        issueDate: now,
        dueDate: due,
        subtotal,
        taxRate: rate,
        taxAmount,
        totalAmount,
        amountPaid: 0,
        balanceDue: totalAmount,
        notes: notes || null,
        periodStart: data.periodStart ? new Date(data.periodStart) : null,
        periodEnd: data.periodEnd ? new Date(data.periodEnd) : null,
        autoGenerated: data.autoGenerated || false,
        items: { create: invoiceItems },
      },
      include: { customer: true, items: true },
    });
  }

  async updateInvoiceStatus(id, status) {
    return this.prisma.ispInvoice.update({
      where: { id },
      data: { status },
    });
  }

  async deleteInvoice(id) {
    return this.prisma.ispInvoice.delete({ where: { id } });
  }

  // ──────────────────────────────────────────────
  // PAYMENTS
  // ──────────────────────────────────────────────

  async recordPayment(data) {
    const { invoiceId, amount, method, reference, notes, paymentDate } = data;

    const invoice = await this.prisma.ispInvoice.findUnique({
      where: { id: invoiceId },
      include: { customer: true },
    });
    if (!invoice) throw new NotFoundException('Invoice not found');

    const payAmount = Number(amount);
    if (payAmount <= 0) throw new BadRequestException('Payment amount must be positive');

    const newAmountPaid = Number(invoice.amountPaid) + payAmount;
    const newBalanceDue = Number(invoice.totalAmount) - newAmountPaid;

    let newStatus = invoice.status;
    if (newBalanceDue <= 0) {
      newStatus = 'PAID';
    } else if (newAmountPaid > 0) {
      newStatus = 'PARTIALLY_PAID';
    }

    const paymentNumber = await this.nextPaymentNumber();

    const [payment] = await this.prisma.$transaction([
      this.prisma.ispPayment.create({
        data: {
          paymentNumber,
          invoiceId,
          amount: payAmount,
          method: method || 'CASH',
          reference: reference || null,
          notes: notes || null,
          paymentDate: paymentDate ? new Date(paymentDate) : new Date(),
        },
      }),
      this.prisma.ispInvoice.update({
        where: { id: invoiceId },
        data: {
          amountPaid: newAmountPaid,
          balanceDue: Math.max(0, newBalanceDue),
          status: newStatus,
          paidDate: newStatus === 'PAID' ? new Date() : null,
        },
      }),
    ]);

    return payment;
  }

  async listPayments({ page = 1, limit = 50, invoiceId } = {}) {
    const where = {};
    if (invoiceId) where.invoiceId = invoiceId;

    const [items, total] = await Promise.all([
      this.prisma.ispPayment.findMany({
        where,
        orderBy: { paymentDate: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        include: {
          invoice: {
            select: { invoiceNumber: true, customerId: true, customer: { select: { firstName: true, lastName: true, pppoeUsername: true } } },
          },
        },
      }),
      this.prisma.ispPayment.count({ where }),
    ]);
    return { items, total, page, pages: Math.ceil(total / limit) };
  }

  // ──────────────────────────────────────────────
  // AUTO-GENERATE MONTHLY INVOICES
  // ──────────────────────────────────────────────

  async generateMonthlyInvoices(servicePlans) {
    // servicePlans: { [profileName]: { description, price } }
    const settings = await this.getSettings();
    const customers = await this.prisma.ispCustomer.findMany({
      where: { status: 'ACTIVE', billingType: 'RECURRING' },
    });

    const now = new Date();
    const periodStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    const monthLabel = now.toLocaleString('en-GB', { month: 'long', year: 'numeric' });

    const results = { generated: 0, skipped: 0, errors: [] };

    for (const cust of customers) {
      try {
        // Check if invoice already exists for this month
        const existing = await this.prisma.ispInvoice.findFirst({
          where: {
            customerId: cust.id,
            periodStart: { gte: periodStart },
            periodEnd: { lte: new Date(periodEnd.getTime() + 86400000) },
          },
        });

        if (existing) {
          results.skipped++;
          continue;
        }

        // Get plan price from servicePlans map (keyed by MikroTik profile name)
        // You'll need to pass the profile name -> price mapping
        const plan = servicePlans?.[cust.pppoeUsername];
        if (!plan || !plan.price) {
          results.skipped++;
          continue;
        }

        await this.createInvoice({
          customerId: cust.id,
          items: [{
            description: `Internet Service - ${plan.description || plan.profileName || 'Monthly'} (${monthLabel})`,
            quantity: 1,
            unitPrice: plan.price,
          }],
          periodStart,
          periodEnd,
          autoGenerated: true,
          notes: `Auto-generated for ${monthLabel}`,
        });

        results.generated++;
      } catch (err) {
        results.errors.push({ customer: cust.pppoeUsername, error: err.message });
      }
    }

    this.logger.log(`Monthly invoices: ${results.generated} generated, ${results.skipped} skipped, ${results.errors.length} errors`);
    return results;
  }

  // ──────────────────────────────────────────────
  // OVERDUE CHECK
  // ──────────────────────────────────────────────

  async markOverdueInvoices() {
    const now = new Date();
    const result = await this.prisma.ispInvoice.updateMany({
      where: {
        status: { in: ['DRAFT', 'SENT'] },
        dueDate: { lt: now },
        balanceDue: { gt: 0 },
      },
      data: { status: 'OVERDUE' },
    });
    this.logger.log(`Marked ${result.count} invoices as overdue`);
    return { count: result.count };
  }

  // ──────────────────────────────────────────────
  // DASHBOARD STATS
  // ──────────────────────────────────────────────

  async getDashboardStats() {
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

    const [
      totalInvoices,
      paidInvoices,
      overdueInvoices,
      draftInvoices,
      totalRevenue,
      monthRevenue,
      totalOutstanding,
    ] = await Promise.all([
      this.prisma.ispInvoice.count(),
      this.prisma.ispInvoice.count({ where: { status: 'PAID' } }),
      this.prisma.ispInvoice.count({ where: { status: 'OVERDUE' } }),
      this.prisma.ispInvoice.count({ where: { status: 'DRAFT' } }),
      this.prisma.ispInvoice.aggregate({ _sum: { amountPaid: true } }),
      this.prisma.ispPayment.aggregate({
        _sum: { amount: true },
        where: { paymentDate: { gte: monthStart } },
      }),
      this.prisma.ispInvoice.aggregate({
        _sum: { balanceDue: true },
        where: { status: { in: ['SENT', 'OVERDUE', 'PARTIALLY_PAID'] } },
      }),
    ]);

    return {
      totalInvoices,
      paidInvoices,
      overdueInvoices,
      draftInvoices,
      totalRevenue: Number(totalRevenue._sum.amountPaid || 0),
      monthRevenue: Number(monthRevenue._sum.amount || 0),
      totalOutstanding: Number(totalOutstanding._sum.balanceDue || 0),
    };
  }

  // ──────────────────────────────────────────────
  // CUSTOMER BILLING SUMMARY
  // ──────────────────────────────────────────────

  async getCustomerBillingSummary(customerId) {
    const [invoices, payments] = await Promise.all([
      this.prisma.ispInvoice.findMany({
        where: { customerId },
        orderBy: { createdAt: 'desc' },
        include: { items: true, payments: true },
      }),
      this.prisma.ispPayment.findMany({
        where: { invoice: { customerId } },
        orderBy: { paymentDate: 'desc' },
      }),
    ]);

    const totalInvoiced = invoices.reduce((sum, inv) => sum + Number(inv.totalAmount), 0);
    const totalPaid = invoices.reduce((sum, inv) => sum + Number(inv.amountPaid), 0);
    const totalOutstanding = invoices.reduce((sum, inv) => sum + Number(inv.balanceDue), 0);
    const overdueCount = invoices.filter((inv) => inv.status === 'OVERDUE').length;

    return {
      invoices,
      payments,
      totalInvoiced,
      totalPaid,
      totalOutstanding,
      overdueCount,
    };
  }
}

module.exports = { IspBillingService };
